name: secure-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - joblib=1.4.2
  - pyarrow=16.1.0
  - matplotlib
  - pyyaml=6.0.1
  - cryptography=42.0.8
  - shap
  - diffprivlib=0.6.4
  - seaborn=0.13.2
  - pip
